### ISSUE TITLE
The deployment using docker-compose has failed

### ISSUE THREAD

**Issue by mxdios** [mayswind/ezbookkeeping#11]
docker-compose.yml 
```
version: "2"
services:
  ezbookkeeping:
    image: mayswind/ezbookkeeping
    container_name: ezbookkeeping
    hostname: "ezbookkeeping"
    ports:
      - "5701:8080"
    environment:
      - "EBK_SERVER_DOMAIN=mydomain"
      - "EBK_SERVER_ENABLE_GZIP=true"
      - "EBK_DATABASE_TYPE=mysql"
      - "EBK_DATABASE_HOST=localhost:3306"
      - "EBK_DATABASE_NAME=ezbookkeeping"
      - "EBK_DATABASE_USER=ezbookkeeping"
      - "EBK_DATABASE_PASSWD=password"
      - "EBK_LOG_MODE=file"
      - "EBK_SECURITY_SECRET_KEY=xxxxxxxxx"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/log/ezbookkeeping:/var/log/ezbookkeeping" # 请确保 UID:GID 是 1000:1000
```

The error log：

2022-10-13 14:37:32 [ERROR] [server.startWebServer] update database table structure failed, because dial tcp 127.0.0.1:3306: connect: connection refused
2022/10/13 14:37:32 Failed to run ezBookkeeping with [/ezbookkeeping/ezbookkeeping server run]: dial tcp 127.0.0.1:3306: connect: connection refused
