### ISSUE TITLE
Issue encountered while setting up https cert with Docker-Compose

### ISSUE THREAD

**Issue by sbbfung** [mayswind/ezbookkeeping#79]
First of all, thank you for creating such beautiful work.
I have use docker compose to setup ezbookkeeping. It works well for http. However, it seems it is unable to set to https mode.
```
services:
  ezbookkeeping:
    image: mayswind/ezbookkeeping
    container_name: ezbookkeeping
    hostname: ezbookkeeping
    ports:
      - "443:8080"
    environment:
      - EBK_SERVER_PROTOCAL=https
      - EBK_SERVER_CERT_FILE=/certificates/certificate.crt
      - EBK_SERVER_CERT_KEY_FILE=/certificates/private.key
      - EBK_SERVER_DOMAIN=some.domain
      - EBK_SERVER_HTTP_PORT=8080
  
      ...REST...
    volumes:
      - ./certificates:/certificates
    networks:
      - some-net
```
and my folder structure
```
.
├── docker-compose.yml
├── certificates
        └── certificate.crt
        └── private.key
```
however, in the docker log, it initialize with 
```
 [initializer.initializeSystem] has loaded configuration {"AppName":"ezBookkeeping","Mode":"production","WorkingPath":"/ezbookkeeping","Protocol":"http","HttpAddr":"0.0.0.0","HttpPort":8080,"Domain":"some.domain","RootUrl":"http://localhost:8080/","CertFile":"","CertKeyFile":"", ...REST...
```
But I checked the env those variables were set. Somehow it did not initialize with those config.
How can I solve this issue? Thanks in advance.

Also checked the endpoint with openssl tool, no certificate. :(
