### ISSUE TITLE
How can I move ezbookkeeping installed with docker to a new server?

### ISSUE THREAD

**Issue by tigerzioo** [mayswind/ezbookkeeping#91]
Tried to map the sqlite database file to host folder but cannot see the sqlite db file under the folder ezbookkeeping_data

```
services:
  ezbookkeeping:
    image: mayswind/ezbookkeeping
    container_name: ezbook
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./ezbookkeeping_data:/data
 ```
